Build ggobi as ggobi.bin and use the shell script to run things.

diff --git a/Install/configure.in b/Install/configure.in
--- a/Install/configure.in
+++ b/Install/configure.in
@@ -13,9 +13,20 @@ dnl executable is.
 
 
 AC_INIT(src/ggobi.c)
- 
+
+GGOBI_HOME=`pwd` 
 
 AC_ARG_ENABLE(embed,--enable-embed Build the ggobi library for embedding in other applications (e.g. R))
+
+AC_ARG_WITH(prefix, [--with-prefix Specify where the files are to be installed (default /usr/local/).],INSTALL_DIR=${with_prefix},INSTALL_DIR="/usr/local")
+
+AC_ARG_WITH(xml, --with-xml Enable reading and writing of XML datasets.)
+AC_ARG_WITH(mysql, --with-mysql Enable reading data from MySQL databases., USE_MYSQL=1)
+AC_ARG_WITH(R,--with-R Install the Rggobi package)
+AC_ARG_WITH(Python,--with-Python Install the Pythonggobi module)
+AC_ARG_WITH(Perl,--with-Perl Install the Perlggobi module)
+
+
 
 
  dnl Check for gtk-config.
@@ -30,49 +41,81 @@ fi
 
 
 DEFAULT_LIB_DIRS="/usr/lib /usr/local/lib /opt/lib"
-DEFAULT_INC_DIRS="/usr/include /usr/local/include /usr/local/src/include"
-
-AC_ARG_WITH(xml, --with-xml Enable reading and writing of XML datasets., USE_XML=1)
-AC_ARG_WITH(mysql, --with-mysql Enable reading data from MySQL databases., USE_MYSQL=1)
+DEFAULT_INC_DIRS="/usr/include /usr/local/include /usr/local/src/include /usr/include/gnome-xml"
 
 
 
+ dnl Start looking for the XML libraries.
+if test -n "${with_xml}" ; then
 
-if test -n "${USE_XML}" ; then
+ echo "with_xml: ${with_xml}"
 
- dnl echo "with_xml: ${with_xml}"
-
+   dnl If the user gave us a --with-xml=value,
+   dnl then use that as the setting for the include
+   dnl and lib directory.
  if test -d ${with_xml} ; then
-  XML_INC_DIRS=$with_xml
-  XML_LIB_DIRS=$with_xml
+  XML_INC_DIRS=${with_xml}
+  XML_LIB_DIRS="${with_xml} ${with_xml}/.libs"
+   dnl Have to get a version that can be used in LD_LIBRARY_PATH,
+   dnl i.e. with the spaces replaced by :
+  XML_LIB_DIRS_PATH=`echo "${with_xml} ${with_xml}/.libs" | sed -e 's/[ \t]*/:/g'`
  fi
 
-   dnl Now find libxml-1.8.7
 
- if test -z "${XML_INC_DIRS}" ; then
-
-   XML_SRC=read_xml.c write_xml.c
+  dnl Now find the libxml-1.8.*
 
    ORIG_CPPFLAGS=$CPPFLAGS
-   for f in ${DEFAULT_INC_DIRS} ; do 
+   for f in $XML_INC_DIRS ${DEFAULT_INC_DIRS} ; do 
      for ext in / /xml ; do
-
-       if test -f $f$ext/mysql.h ; then
-         MYSQL_INC_DIRS=$f$ext 
+       TMP=""
+       if test -f $f$ext/parser.h ; then
+         TMP=$f$ext 
+         XML_INC_DIRS=${TMP}
        fi
 dnl      CPPFLAGS="${ORIG_CPPFLAGS} -I$f$ext"
 dnl      AC_CHECK_HEADER(parserInternals.h, XML_INC_DIRS=$f$ext)
 
-      if test -n "${XML_INC_DIRS}" ; then
-        echo "Found XML include file(s): $XML_INC_DIRS"
+      if test "${TMP}"  != "" ; then
+        echo "Found XML include file(s): $XML_INC_DIRS, $TMP"
         break
       fi
 
      done
+     if test "${TMP}" != "" ; then 
+       break;
+     fi
    done
 
- fi
-  XML_UTILS=xmlConvert
+
+  dnl now we should test for the library.
+
+
+  if test "${TMP}" = "" ; then
+    echo "Cannot find the XML header files. Please specify these via"
+    echo "--with-xml=<dir>, or by setting the XML_INC_DIRS environment variable."
+    exit 2
+  else
+    XML_UTILS=xmlConvert
+    USE_XML="USE_XML=1"
+    XML_SRC="read_xml.c write_xml.c"
+    XML_CFLAG_DEFINES="-DUSE_XML=1"
+    enable_embed="yes"
+dnl -DDIR_SEPARATOR=\"'/'\""
+  fi
+fi
+
+if test -n "${with_R}" ; then
+
+  if test -d Rggobi ; then
+    WITH_R=1
+    AC_PATH_PROG(R_BIN,R,[Cannot find the R executable])
+    if test -d $with_R ; then
+      R_PKG_DIR="-l $with_R"
+    fi
+    PACKAGES="Rggobi ${PACKAGES}"
+  else
+    echo "You cannot install the Rggobi interface without first downloading Rggobi.tar.gz"
+  fi
 fi
 
 
@@ -124,28 +167,33 @@ dnl      AC_CHECK_HEADER(mysql.h, MYSQL_INC_DIRS=$f$ext)
     echo "Cannot find libxml"
     exit 1;
    else
-     echo "Using libxml from ${LIBS}"
+     echo "Using libmysql from ${LIBS}"
    fi
 
   fi
 
+  USE_MYSQL="USE_MYSQL=1"
 fi
 
 TOP=`pwd`
 MV=mv
 
+
 if test "${enable_embed}" = "yes" ; then
    EMBED="lib/libggobi.so"
 fi
 
-AC_SUBST(EMBED)
+GGOBI_ROOT=`pwd`
+AC_SUBST(GGOBI_ROOT)
 
+AC_SUBST(EMBED)
 AC_SUBST(MV)
 
 AC_SUBST(TOP)
 
 AC_SUBST(XML_UTILS)
 AC_SUBST(USE_XML)
+AC_SUBST(XML_CFLAG_DEFINES)
 AC_SUBST(USE_MYSQL)
 
 AC_SUBST(XML_SRC)
@@ -153,8 +201,20 @@ AC_SUBST(MYSQL_SRC)
 
 AC_SUBST(XML_INC_DIRS)
 AC_SUBST(XML_LIB_DIRS)
+AC_SUBST(XML_LIB_DIRS_PATH)
 
 AC_SUBST(MYSQL_INC_DIRS)
 AC_SUBST(MYSQL_LIB_DIRS)
 
-AC_OUTPUT(Makeconf GNUmakefile src/GNUmakefile gtkext/src/GNUmakefile)
+AC_SUBST(GGOBI_HOME)
+
+AC_SUBST(INSTALL_DIR)
+
+AC_SUBST(PACKAGES)
+
+AC_SUBST(R_PKG_DIR)
+AC_SUBST(R_BIN)
+
+AC_OUTPUT(Makeconf GNUmakefile src/GNUmakefile gtkext/src/GNUmakefile bin/setLD.csh  bin/setLD.bsh bin/ggobi)
+
+chmod +x bin/ggobi
